# Generated by cucumber-sinatra. (Tue Mar 29 12:29:00 +0100 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BaseApplication

class BaseApplicationWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BaseApplicationWorld.new
end
